### ISSUE TITLE
Bluestacks

### ISSUE THREAD

**Issue by pixo2000** [pyclashbot/py-clash-bot#378]
I have the Problem that i cannot install the Emulator. The only emulator my pc can run is Bluestacks 5. If you are using image recognition, i dont think that it would be hard to add support for Bluestacks.

**Comment by martinmiglio** [comment]
MEmu and bluestacks run on the same underlying technology. This program is highly bound to MEmu as it controls all aspects of the emulator, including the initialization and configuration. Switching to bluestacks would be a large task.

Instead of putting in the time to add bluestacks support, we plan to include support for the Google Play PC version of Clash Royale. Supporting this would be preferable over both MEmu and bluestacks as it offers a more native connection the the application.
